package za.co.idea.ip.hook.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import za.co.idea.ip.hook.model.IpGroup;
import za.co.idea.ip.hook.service.IpGroupLocalServiceUtil;

/**
 * The extended model base implementation for the IpGroup service. Represents a row in the &quot;ip_group&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link IpGroupImpl}.
 * </p>
 *
 * @author VMPattamatta
 * @see IpGroupImpl
 * @see za.co.idea.ip.hook.model.IpGroup
 * @generated
 */
public abstract class IpGroupBaseImpl extends IpGroupModelImpl
    implements IpGroup {
    /**
	 * 
	 */
	private static final long serialVersionUID = -3124491817685348680L;

	/*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a ip group model instance should use the {@link IpGroup} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            IpGroupLocalServiceUtil.addIpGroup(this);
        } else {
            IpGroupLocalServiceUtil.updateIpGroup(this);
        }
    }
}
