package za.co.idea.ip.hook.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import za.co.idea.ip.hook.model.IpLogin;
import za.co.idea.ip.hook.service.IpLoginLocalServiceUtil;

/**
 * The extended model base implementation for the IpLogin service. Represents a row in the &quot;ip_login&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link IpLoginImpl}.
 * </p>
 *
 * @author VMPattamatta
 * @see IpLoginImpl
 * @see za.co.idea.ip.hook.model.IpLogin
 * @generated
 */
public abstract class IpLoginBaseImpl extends IpLoginModelImpl
    implements IpLogin {
    /**
	 * 
	 */
	private static final long serialVersionUID = 3166418712588602985L;

	/*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a ip login model instance should use the {@link IpLogin} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            IpLoginLocalServiceUtil.addIpLogin(this);
        } else {
            IpLoginLocalServiceUtil.updateIpLogin(this);
        }
    }
}
