package za.co.idea.ip.hook.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import za.co.idea.ip.hook.model.IpSecqList;
import za.co.idea.ip.hook.service.IpSecqListLocalServiceUtil;

/**
 * The extended model base implementation for the IpSecqList service. Represents a row in the &quot;ip_secq_list&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link IpSecqListImpl}.
 * </p>
 *
 * @author VMPattamatta
 * @see IpSecqListImpl
 * @see za.co.idea.ip.hook.model.IpSecqList
 * @generated
 */
public abstract class IpSecqListBaseImpl extends IpSecqListModelImpl
    implements IpSecqList {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1570231303223247180L;

	/*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a ip secq list model instance should use the {@link IpSecqList} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            IpSecqListLocalServiceUtil.addIpSecqList(this);
        } else {
            IpSecqListLocalServiceUtil.updateIpSecqList(this);
        }
    }
}
