package za.co.idea.ip.hook.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import za.co.idea.ip.hook.model.IpUser;
import za.co.idea.ip.hook.service.IpUserLocalServiceUtil;

/**
 * The extended model base implementation for the IpUser service. Represents a row in the &quot;ip_user&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link IpUserImpl}.
 * </p>
 *
 * @author VMPattamatta
 * @see IpUserImpl
 * @see za.co.idea.ip.hook.model.IpUser
 * @generated
 */
public abstract class IpUserBaseImpl extends IpUserModelImpl implements IpUser {
    /**
	 * 
	 */
	private static final long serialVersionUID = 601298837548322098L;

	/*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a ip user model instance should use the {@link IpUser} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            IpUserLocalServiceUtil.addIpUser(this);
        } else {
            IpUserLocalServiceUtil.updateIpUser(this);
        }
    }
}
