package za.co.idea.ip.hook.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the IpGroup service. Represents a row in the &quot;ip_group&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link za.co.idea.ip.hook.model.impl.IpGroupModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link za.co.idea.ip.hook.model.impl.IpGroupImpl}.
 * </p>
 *
 * @author VMPattamatta
 * @see IpGroup
 * @see za.co.idea.ip.hook.model.impl.IpGroupImpl
 * @see za.co.idea.ip.hook.model.impl.IpGroupModelImpl
 * @generated
 */
public interface IpGroupModel extends BaseModel<IpGroup> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a ip group model instance should use the {@link IpGroup} interface instead.
     */

    /**
     * Returns the primary key of this ip group.
     *
     * @return the primary key of this ip group
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this ip group.
     *
     * @param primaryKey the primary key of this ip group
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the group ID of this ip group.
     *
     * @return the group ID of this ip group
     */
    public long getGroupId();

    /**
     * Sets the group ID of this ip group.
     *
     * @param groupId the group ID of this ip group
     */
    public void setGroupId(long groupId);

    /**
     * Returns the group admin ID of this ip group.
     *
     * @return the group admin ID of this ip group
     */
    public long getGroupAdminId();

    /**
     * Sets the group admin ID of this ip group.
     *
     * @param groupAdminId the group admin ID of this ip group
     */
    public void setGroupAdminId(long groupAdminId);

    /**
     * Returns the group parent ID of this ip group.
     *
     * @return the group parent ID of this ip group
     */
    public long getGroupParentId();

    /**
     * Sets the group parent ID of this ip group.
     *
     * @param groupParentId the group parent ID of this ip group
     */
    public void setGroupParentId(long groupParentId);

    /**
     * Returns the group name of this ip group.
     *
     * @return the group name of this ip group
     */
    @AutoEscape
    public String getGroupName();

    /**
     * Sets the group name of this ip group.
     *
     * @param groupName the group name of this ip group
     */
    public void setGroupName(String groupName);

    /**
     * Returns the group status of this ip group.
     *
     * @return the group status of this ip group
     */
    @AutoEscape
    public String getGroupStatus();

    /**
     * Sets the group status of this ip group.
     *
     * @param groupStatus the group status of this ip group
     */
    public void setGroupStatus(String groupStatus);

    /**
     * Returns the group email of this ip group.
     *
     * @return the group email of this ip group
     */
    @AutoEscape
    public String getGroupEmail();

    /**
     * Sets the group email of this ip group.
     *
     * @param groupEmail the group email of this ip group
     */
    public void setGroupEmail(String groupEmail);

    /**
     * Returns the group is core of this ip group.
     *
     * @return the group is core of this ip group
     */
    @AutoEscape
    public String getGroupIsCore();

    /**
     * Sets the group is core of this ip group.
     *
     * @param groupIsCore the group is core of this ip group
     */
    public void setGroupIsCore(String groupIsCore);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(IpGroup ipGroup);

    @Override
    public int hashCode();

    @Override
    public CacheModel<IpGroup> toCacheModel();

    @Override
    public IpGroup toEscapedModel();

    @Override
    public IpGroup toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
