package za.co.idea.ip.hook.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the IpLogin service. Represents a row in the &quot;ip_login&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link za.co.idea.ip.hook.model.impl.IpLoginModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link za.co.idea.ip.hook.model.impl.IpLoginImpl}.
 * </p>
 *
 * @author VMPattamatta
 * @see IpLogin
 * @see za.co.idea.ip.hook.model.impl.IpLoginImpl
 * @see za.co.idea.ip.hook.model.impl.IpLoginModelImpl
 * @generated
 */
public interface IpLoginModel extends BaseModel<IpLogin> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a ip login model instance should use the {@link IpLogin} interface instead.
     */

    /**
     * Returns the primary key of this ip login.
     *
     * @return the primary key of this ip login
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this ip login.
     *
     * @param primaryKey the primary key of this ip login
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the login ID of this ip login.
     *
     * @return the login ID of this ip login
     */
    public long getLoginId();

    /**
     * Sets the login ID of this ip login.
     *
     * @param loginId the login ID of this ip login
     */
    public void setLoginId(long loginId);

    /**
     * Returns the login user ID of this ip login.
     *
     * @return the login user ID of this ip login
     */
    public long getLoginUserId();

    /**
     * Sets the login user ID of this ip login.
     *
     * @param loginUserId the login user ID of this ip login
     */
    public void setLoginUserId(long loginUserId);

    /**
     * Returns the login user uuid of this ip login.
     *
     * @return the login user uuid of this ip login
     * @throws SystemException if a system exception occurred
     */
    public String getLoginUserUuid() throws SystemException;

    /**
     * Sets the login user uuid of this ip login.
     *
     * @param loginUserUuid the login user uuid of this ip login
     */
    public void setLoginUserUuid(String loginUserUuid);

    /**
     * Returns the login name of this ip login.
     *
     * @return the login name of this ip login
     */
    @AutoEscape
    public String getLoginName();

    /**
     * Sets the login name of this ip login.
     *
     * @param loginName the login name of this ip login
     */
    public void setLoginName(String loginName);

    /**
     * Returns the login pwd of this ip login.
     *
     * @return the login pwd of this ip login
     */
    @AutoEscape
    public String getLoginPwd();

    /**
     * Sets the login pwd of this ip login.
     *
     * @param loginPwd the login pwd of this ip login
     */
    public void setLoginPwd(String loginPwd);

    /**
     * Returns the login last dt of this ip login.
     *
     * @return the login last dt of this ip login
     */
    public Date getLoginLastDt();

    /**
     * Sets the login last dt of this ip login.
     *
     * @param loginLastDt the login last dt of this ip login
     */
    public void setLoginLastDt(Date loginLastDt);

    /**
     * Returns the login sec q of this ip login.
     *
     * @return the login sec q of this ip login
     */
    public int getLoginSecQ();

    /**
     * Sets the login sec q of this ip login.
     *
     * @param loginSecQ the login sec q of this ip login
     */
    public void setLoginSecQ(int loginSecQ);

    /**
     * Returns the login sec a of this ip login.
     *
     * @return the login sec a of this ip login
     */
    @AutoEscape
    public String getLoginSecA();

    /**
     * Sets the login sec a of this ip login.
     *
     * @param loginSecA the login sec a of this ip login
     */
    public void setLoginSecA(String loginSecA);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(IpLogin ipLogin);

    @Override
    public int hashCode();

    @Override
    public CacheModel<IpLogin> toCacheModel();

    @Override
    public IpLogin toEscapedModel();

    @Override
    public IpLogin toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
