package za.co.idea.ip.hook.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the IpSecqList service. Represents a row in the &quot;ip_secq_list&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link za.co.idea.ip.hook.model.impl.IpSecqListModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link za.co.idea.ip.hook.model.impl.IpSecqListImpl}.
 * </p>
 *
 * @author VMPattamatta
 * @see IpSecqList
 * @see za.co.idea.ip.hook.model.impl.IpSecqListImpl
 * @see za.co.idea.ip.hook.model.impl.IpSecqListModelImpl
 * @generated
 */
public interface IpSecqListModel extends BaseModel<IpSecqList> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a ip secq list model instance should use the {@link IpSecqList} interface instead.
     */

    /**
     * Returns the primary key of this ip secq list.
     *
     * @return the primary key of this ip secq list
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this ip secq list.
     *
     * @param primaryKey the primary key of this ip secq list
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the isl ID of this ip secq list.
     *
     * @return the isl ID of this ip secq list
     */
    public long getIslId();

    /**
     * Sets the isl ID of this ip secq list.
     *
     * @param islId the isl ID of this ip secq list
     */
    public void setIslId(long islId);

    /**
     * Returns the isl desc of this ip secq list.
     *
     * @return the isl desc of this ip secq list
     */
    @AutoEscape
    public String getIslDesc();

    /**
     * Sets the isl desc of this ip secq list.
     *
     * @param islDesc the isl desc of this ip secq list
     */
    public void setIslDesc(String islDesc);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(IpSecqList ipSecqList);

    @Override
    public int hashCode();

    @Override
    public CacheModel<IpSecqList> toCacheModel();

    @Override
    public IpSecqList toEscapedModel();

    @Override
    public IpSecqList toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
